### ISSUE TITLE
How to make work with @each loop

### ISSUE THREAD

**Issue by pattiereaves** [kossnocorp/decss#12]
I'm trying to make this work with [postcss-each](https://github.com/outpunk/postcss-each) and I'm running into some issues.

What I want to do is something like 

React:
```jsx
<MyComponent color="red" />
```
CSS:
```css
@each $color in var(--colors) {
  .MyComponent-color-$color { background-color: $color; }
}
```

Where I'm getting an error `Cannot read property '1' of null` on this line in [getComponents](https://github.com/kossnocorp/decss/blob/master/index.js#L99) in the console, and none of my react application loads. Is there a better way to do this?
